name: CMake CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - "include/**"
      - "test/**"
      - ".github/actions/**"
      - ".github/workflows/cmake.yml"

env:
  CXX: /usr/bin/clang++-12
  CC: /usr/bin/clang-12

jobs:
  min-req:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        uses: lukka/get-cmake@v3.15.7
      - uses: ./.github/actions/install/gtest
      - uses: ./.github/actions/install/curl
      - name: Build Tests
        run: |
          mkdir build
          cd build
          cmake .. -DASYNCPP_BUILD_TEST=ON -G 'Unix Makefiles'
          cmake --build .
      - name: Run Tests
        run: |
          cd build
          ./asyncpp_curl-test