name: CMake CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - "include/**"
      - "test/**"
      - ".github/actions/**"
      - ".github/workflows/cmake.yml"

env:
  CXX: /usr/bin/clang++-12
  CC: /usr/bin/clang-12

jobs:
  min-req:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache CMake
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: cmake-3.15.7
          key: ${{ runner.os }}-cmake-min-req-3.15.7
      - name: Build cmake
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: |
          wget https://cmake.org/files/v3.15/cmake-3.15.7.tar.gz
          tar -zxf cmake-3.15.7.tar.gz
          cd cmake-3.15.7
          ./bootstrap
          make -j $(nproc)
      - name: Install cmake
        run: |
          cd cmake-3.15.7
          sudo make install
      - uses: ./.github/actions/install/gtest
      - uses: ./.github/actions/install/curl
      - name: Build Tests
        run: |
          mkdir build
          cd build
          cmake .. -DASYNCPP_BUILD_TEST=ON -G 'Unix Makefiles'
          cmake --build .
      - name: Run Tests
        run: |
          cd build
          ./asyncpp_curl-test